steps:
- name: gcr.io/spinnaker-marketplace/gradle_cache
  env: ["GRADLE_USER_HOME=/gradle_cache/.gradle"]
  entrypoint: "bash"
  args: ["-c", "./gradlew echo-web:installDist -x test"]
- name: gcr.io/cloud-builders/docker
  # Exclude echo from the slim docker builds since the alpine base image
  # (which is used in the slim builds) is missing a package gRPC needs to
  # establish pub/sub listeners.
  args: ["build", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME", "-f", "Dockerfile", "."]
  env: ["GRADLE_USER_HOME=/gradle_cache/.gradle"]
images:
- gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME
timeout: 3600s
options:
  machineType: N1_HIGHCPU_8
