FROM ubuntu:bionic
MAINTAINER sig-platform@spinnaker.io
COPY echo-web/build/install/echo /opt/echo
RUN apt-get update && apt-get -y install openjdk-11-jre-headless wget
RUN adduser --disabled-login --system spinnaker
RUN mkdir -p /opt/spinnaker/plugins && chown -R spinnaker:nogroup /opt/spinnaker/plugins
USER spinnaker
CMD ["/opt/echo/bin/echo"]
