server:
  port: 8089

spinnaker:
  cassandra:
    cluster: 'spinnaker'
    keyspace: 'echo'
  baseUrl: 'http://localhost:9000'

front50:
  baseUrl: 'http://localhost:8080'

orca:
  baseUrl: 'http://localhost:8083'

search:
  index: 'event_history'

management.health.mail.enabled: false

spring.freemarker.enabled: false

webhooks:
  artifacts:
    enabled: false
    sources: []

resilience4j.circuitbreaker:
  instances:
    telemetry:
      # Startup config...
      registerHealthIndicator: true
      # Warming up...
      minimumNumberOfCalls: 5
      slidingWindowSize: 10
      slidingWindowType: COUNT_BASED
      # When tripped...
      waitDurationInOpenState: 12h
      # Try to get back to a working state...
      permittedNumberOfCallsInHalfOpenState: 1
